### PR TITLE
Simple string hash for large strings

### PR DESCRIPTION
**Pull request by funny-falcon**
it fits into i386 registers, do not use multiplication, and consumes more than 2 bytes per cycle
(on Haswell compiled as i386)

+ add check for hashsum equality in chain traversion.

### CODE REVIEW

**Comment by funny-falcon** [comment]
Probably closes #168

**Comment by funny-falcon** [comment]
Note, it doesn't protect from DoS hash-collision.
There is no fast enough (from LuaJIT view of point) platform independent hash function able to protect from.

Simplest platform independent function which I know that can resist "Seed Independent Collision" attack is at least three times slower, and it uses multiplication.

**Comment by bungle** [comment]
@funny-falcon Great!

I can confirm that this also fixes #168.

**Comment by bungle** [comment]
This is even better with latest changes to this pull request.

**Comment by funny-falcon** [comment]
Obsoleted by https://github.com/LuaJIT/LuaJIT/pull/174

**Pull request closed without merging**
