### PR TITLE
FFI callback docs: "self-calling" :free() is safe

### PR DESCRIPTION
**Pull request by vcunat**
https://www.freelists.org/post/luajit/Safely-free-FFI-callback-while-inside-of-it,1

### CODE REVIEW

**Comment by vcunat** [comment]
@MikePall: I assume you just haven't noticed this trivial PR?

**Comment by vcunat** [comment]
So... it won't be guaranteed as safe?  Or some other reason why wontfix?

**Comment by MikePall** [comment]
It's safe for now. But any guarantee given in the docs may complicate future enhancements, because somebody *will* rely on the behavior.

**Comment by vcunat** [comment]
Ah, OK.  Yes, we've been relying it :-)

**Pull request closed without merging**
