### PR TITLE
unbind lj_parse.c and lib_ffi.c from lj_str_new

### PR DESCRIPTION
**Pull request by funny-falcon**
Add small string hash function, so lj_parse.c and lib.ffi.c do not depends on hash calculated in lj_str_new.

This will allow embedders to easier switch hashsum algorithm in lj_str_new if they wants.

### CODE REVIEW

**Comment by iehrlich** [comment]
First of all, I like where this is going. However, to my mind, this patch adds more magic instead of making it less.

I mean, the problem you are trying to solve is really important in the mid- and long-run, but I think that the better solution here is to remove this wannabe-hashes from the code completely. Instead of this, you might create and fix strings like "align", "packed", "mode" etc at the startup. When creating these, you might use `GCstr.unused` or possibly even `GCstr.reserved` to store a numeric constant (`FFI_keyword_align` or something like that), and switch against these constants.

This will allow you to:

- Remove the necessity of computing simplier hashes compile-time;
- Add more clarity to the code;
- Rely on existing string differentiation mechanism, does not matter what it is, it will still be isolated in lj_str_new;

**Comment by funny-falcon** [comment]
While I agree about ugliness of compile-time hashes, I donn't think this non-performance critical code needs additional complexity.

I really believe, `strcmp` will play well here (especially considering `__builtin_strcmp`)(probably, with switch on first letter and then check with `strcmp`).

But I doubt @MikePall will accept `strcmp` :-(

**Comment by funny-falcon** [comment]
Alternative implementation using switch on first letter and check by strcmp: #244

**Comment by funny-falcon** [comment]
@iehrlich @MikePall I've made other commit to separate branch:
- change magic numbers to constant-macroses
- auto-generate file with macroses with (mini)lua during build (and move "small hash function" to this autogenerated file for consistency)

https://github.com/LuaJIT/LuaJIT/compare/1131fa22a23c6284ba5945bffb3dcd6deef2076e...funny-falcon:0b4b03014a7c319708fb4403f5b70f4868d5b658

If you find it less magic, I'll push that commit to this pull request.

**Comment by funny-falcon** [comment]
I've changed pull request to 'script-generated' hash values.

**Comment by MikePall** [comment]
A solution with a different approach was added.

**Comment by funny-falcon** [comment]
https://github.com/LuaJIT/LuaJIT/commit/70f4b15ee45a6137fe6b48b941faea79d72f7159

**Pull request closed without merging**
