### PR TITLE
[WIP] backport operators from 5.3

### PR DESCRIPTION
**Pull request by fperrad**
Work In Progress:
- only `vm_x86`
- `libbc` not regenerated

Any feedback wellcome.

### CODE REVIEW

**Comment by daurnimator** [comment]
I'm excited for this!
Currently I have to hide bit operators behind `loadstring[[...]]` to prevent them being a syntax error.

**Comment by MikePall** [comment]
First, I think this PR is too invasive to land in 2.1. It would also necessitate changing the 2.1 bytecode format, which was stable for quite a long time (though this is not guaranteed in beta).

So, take your time. I wouldn't recommend to start with the other ports until all open questions have been resolved and until the x86 code is final.

Moving the discussion over to #63.

**Comment by fperrad** [comment]
rebased on tag beta3

**Comment by timofonic** [comment]
@fperrad @daurnimator Yes! Thanks a lot!

@MikePall So when is LuaJit going to evolve? People are starting to joke and badmouthing about LuaJit development :/

**Pull request closed without merging**
