### PR TITLE
Add support for LoongArch64

### PR DESCRIPTION
**Pull request by sophie-zhao**

### CODE REVIEW

**Comment by sophie-zhao** [comment]
Hi @MikePall

This patchset is adding basic LoongArch64 support in LuaJIT (interpreter and JIT-compiler code).

LoongArch is a new RISC ISA, which is independently designed by Loongson Technology. LoongArch includes a reduced 32-bit version (LA32R), a standard 32-bit version (LA32S) and a 64-bit version (LA64).

Loongson and LoongArch documentations:
  https://github.com/loongson/LoongArch-Documentation

The ISAs, ABIs and OS we support are:
     ISA: LoongArch64
     ABI: LP64d
     OS: Linux

Open-source tool chain (Binutils, Gcc and glibc) are already upstream.

We have ran the test set (https://github.com/LuaJIT/LuaJIT-test-cleanup), and the result was: 

    505 passed, 3 failed
    to run just failing tests, pass command line arguments: 363 365 366


We are prepared to sponsor the initial review and the extra effort for continued maintenance.
What preparations do we need to do?

**Comment by MikePall** [comment]
OK, I've checked the requirements:

* Architecture is, or will be relevant. Enough funding, a big enough target market, potential to be competitive, well-designed, not archaic or marginal, unlikely to die within the next 5 years.
* Architecture owner is willing to continuously and adequately fund LuaJIT for initial review and continued maintenance.
* Submitted code is based on v2.1 HEAD, GC64 mode, complete with interpreter, JIT compiler backend and FFI. Overall code quality looks good on first sight, but needs detailed review.
* ISA docs: Sufficient, from what I can see. LuaJIT doesn't need SIMD instructions.
* QEMU user-mode: I see that 7.1 will include LoongArch64. Let's hope it's stable enough, so one doesn't have to chase bugs in the emulator.
* Cross toolchain: Mostly there, except:
  * The pre-built package is missing a cross-GDB.
  * The included `loongarch64-unknown-linux-gnu-ar` is broken.

Looks good to me, so:

Please provide a business contact mail address with whom I can discuss a CLA, sponsorship and maintenance contract.

**Comment by sophie-zhao** [comment]
Hi, @MikePall , we have confirmed these two questions:
> Cross toolchain: Mostly there, except:
> 
>     * The pre-built package is missing a cross-GDB.
> 
>     * The included `loongarch64-unknown-linux-gnu-ar` is broken.

(1) Currently there is no Cross-GDB binary, we will provide it later.
(2) You can try the following cross toolchain, the `loongarch64-unknown-linux-gnu-ar` included is available:
https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/download/5.0/loongarch64-clfs-5.1-cross-tools-gcc-glibc.tar.xz



> Please provide a business contact mail address with whom I can discuss a CLA, sponsorship and maintenance contract.

You can contact me though email:  zhaoxiaolin@loongson.cn

**Comment by sophie-zhao** [comment]
@MikePall  We still very much hope that the community can support the loongarch64 architecture. Regarding matters such as funding and maintenance, we hope to continue to communicate with you and respect your hard work. Hope you check your mail and give us an answer.
Thanks.

**Pull request closed without merging**
