### PR TITLE
refactor table.maxn with LJLIB_LUA

### PR DESCRIPTION
**Pull request by fperrad**

### CODE REVIEW

**Comment by daurnimator** [comment]
o.o who is actually using `table.maxn` these days?

That said, the new code is smaller and simpler.

**Comment by corsix** [comment]
> That said, the new code is smaller and simpler.

Though I'd suspect slower, not necessarily behaviour-preserving (namely, what if someone has replaced the global `type`?), and still doesn't give you a JIT-compilable function.

**Comment by funny-falcon** [comment]
It is not only "interpreted vs compilled" slower. It is algorithmically slower.
I'm downvoting.

**Comment by MikePall** [comment]
`table.maxn` is an abomination that should not be used by anyone and should have never been added to Lua. Sadly, we have to keep it for compatibility.

The exact behavior must be kept for compatibility. And due to its irrelevance in practice, any effort spent on this function is wasted and will be closed with wontfix.

**Pull request closed without merging**
