### PR TITLE
backport coroutine.isyieldable from 5.3

### PR DESCRIPTION
**Pull request by fperrad**

### CODE REVIEW

**Comment by daurnimator** [comment]
`coroutine.isyieldable` does more than check if it's in the main thread: it will also return false if e.g. in a metamethod or in a function called via lua_pcallk without a continuation.

**Comment by fperrad** [comment]
LuaJIT claims to be fully resumable, see https://github.com/LuaJIT/LuaJIT/blob/master/doc/extensions.html#L236-L239

**Comment by daurnimator** [comment]
You still can't from inside of e.g. a `lua_pcall`'d function (when the pcall is done from the C side).

**Comment by fperrad** [comment]
Refactored with `cframe_canyield`

**Comment by daurnimator** [comment]
Could this be exported as a C function (`lua_isyieldable`) as well?

**Comment by fperrad** [comment]
Yes, I think it's doable, but in this PR.
The goal of this PR is to backport a part of the Lua 5.3 library, not the Lua 5.3 C/API.

**Comment by MikePall** [comment]
Aplied. Thanks!

**Pull request closed without merging**
