### PR TITLE
DynASM/x86: Add AVX and AVX2 opcodes.

### PR DESCRIPTION
**Pull request by corsix**
Relates to #92.

### CODE REVIEW

**Comment by lukego** [comment]
Is disassembly working on VEX instructions?

I did a quick test after applying the patch to the dynasm we use in Snabb Switch (import of Cosmin's Lua-based branch) and dumping this code:

```
| vmovdqu [0], ymm0
| ret
```

I see this disassembly:

```
7fe9b1052000  C5                (unknown)
7fe9b1052001  FE7F              (unknown)
7fe9b1052003  0425              add al, 0x25
7fe9b1052005  0000              add [rax], al
7fe9b1052007  0000              add [rax], al
7fe9b1052009  C3                ret
```

**Comment by corsix** [comment]
Disassembly using which tool? If you mean by LuaJIT's `jit/dis_x86.lua`, then no, I'll need to investigate that.

**Comment by lukego** [comment]
Yep I mean with `jit/dis_x86.lua`. Supporting the instructions there would be wonderful. I always dump the machine code this way to sanity-check the code I am generating.

**Comment by corsix** [comment]
New version pushed, including disassembly support.

**Comment by lukego** [comment]
Awesome!

```
7fef965ea000  C5FE7F0425000000. vmovdqu [0x00000000], ymm0
7fef965ea009  C3                ret
```

**Comment by MikePall** [comment]
Applied. Thanks.

**Pull request closed without merging**
