### PR TITLE
[RFC] Experimental implementation of Windows ARM64 support

### PR DESCRIPTION
**Pull request by stephenjust**
Some work-in-progress code towards Windows on ARM64 support. (See #593)

This PR should not be merged directly, it's more to provide a reviewable partial solution to Windows ARM64 support. Feel free to build off this work.

This will build with msys2 clangarm64 or MSVC 2022 ARM native tools. (Presumably cross tools as well, but I'm running native.)

Things of note:

* MSVC compiler bug triggered by lj_ir.c, passing /Oi- to the compiler works around the issue. I don't see this issue for other compiler architectures.
* I don't know how to implement the SEH part.
* I'm hitting a weird issue where the version of vm_arm64.dasc processed by dynasm has an infinite loop in vm_growstack_l, L438 seems to point back to itself when running the output in a debugger.

```
> ./luajit -e 'print("foo")'
foo
```

```
> ./luajit -e 'print(require("lgi")._VERSION)'
... triggers infinite loop, connect a debugger and step into function ...
```

image

(According to vm_arm64.dasc, it should be jumping to `lj_state_growstack`.)

### CODE REVIEW

**Comment by MikePall** [comment]
Branches looping back are usually a symptom of missing or wrong relocation records.

Check the relocation types with `objdump -r` for a trivial object file calling an external function:
```C
extern void foo(void);
void bar(void) { foo(); }
```
Then compare to `PEOBJ_RELOC_*`.

**Comment by vanc** [comment]
I was porting LuaJIT to Windows ARM64. Spent some time on the SEH support, mostly looking at [MS documentation](https://learn.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-170#unwind-codes), and used tools, including dumpbin from VisualStudio, llvm-objdump from Clang to verify the generated SEH info. Even though it looks correct to me, but SEH didn't work. I could trigger the exception handler, but then things stuck. My workaround was to enable internal unwinding (-DLUAJIT_UNWIND_INTERNAL), and everything works (except exeptions thrown from external DLLs). I tested with the test suites from the discontinued moonjit project (inheritted from Mike's test suite).

Here is the buildvm_pe.c patch.

```
--- a/src/host/buildvm_peobj.c
+++ b/src/host/buildvm_peobj.c
@@ -9,7 +9,7 @@
 #include "buildvm.h"
 #include "lj_bc.h"
 
-#if LJ_TARGET_X86ORX64
+#if LJ_TARGET_WINDOWS
 
 /* Context for PE object emitter. */
 static char *strtab;
@@ -76,6 +76,19 @@
   uint8_t unused[3];
 } PEsymaux;
 
+#if LJ_TARGET_ARM64
+#pragma pack(push, 1)
+typedef struct UnwindInfo {
+  uint32_t FunctionLength : 18;
+  uint32_t Version : 2;
+  uint32_t X : 1;
+  uint32_t E : 1;
+  uint32_t EpilogCount : 5;
+  uint32_t CodeWords : 5;
+} UnwindInfo;
+#pragma pack(pop)
+#endif
+
 /* Cannot use sizeof, because it pads up to the max. alignment. */
 #define PEOBJ_SYM_SIZE	(8+4+2+2+1+1)
 
@@ -93,6 +106,13 @@
 #define PEOBJ_RELOC_ADDR32NB	0x03
 #define PEOBJ_RELOC_OFS		0
 #define PEOBJ_TEXT_FLAGS	0x60500020  /* 60=r+x, 50=align16, 20=code. */
+#elif LJ_TARGET_ARM64
+#define PEOBJ_ARCH_TARGET	0xaa64
+#define PEOBJ_RELOC_REL32	0x03  /* MS: BRANCH26 */
+#define PEOBJ_RELOC_DIR32	0x01
+#define PEOBJ_RELOC_ADDR32NB	0x02
+#define PEOBJ_RELOC_OFS		-4
+#define PEOBJ_TEXT_FLAGS	0x60500020  /* 60=r+x, 50=align16, 20=code. */
 #endif
 
 /* Section numbers (0-based). */
@@ -100,7 +120,7 @@
   PEOBJ_SECT_ABS = -2,
   PEOBJ_SECT_UNDEF = -1,
   PEOBJ_SECT_TEXT,
-#if LJ_TARGET_X64
+#if LJ_TARGET_X64 || LJ_TARGET_ARM64
   PEOBJ_SECT_PDATA,
   PEOBJ_SECT_XDATA,
 #elif LJ_TARGET_X86
@@ -188,18 +208,28 @@
   /* Flags: 60 = read+execute, 50 = align16, 20 = code. */
   pesect[PEOBJ_SECT_TEXT].flags = PEOBJ_TEXT_FLAGS;
 
-#if LJ_TARGET_X64
+#if LJ_TARGET_X64 || LJ_TARGET_ARM64
   memcpy(pesect[PEOBJ_SECT_PDATA].name, ".pdata", sizeof(".pdata")-1);
   pesect[PEOBJ_SECT_PDATA].ofs = sofs;
+  #if LJ_TARGET_X64
   sofs += (pesect[PEOBJ_SECT_PDATA].size = 6*4);
   pesect[PEOBJ_SECT_PDATA].relocofs = sofs;
   sofs += (pesect[PEOBJ_SECT_PDATA].nreloc = 6) * PEOBJ_RELOC_SIZE;
+  #else
+  sofs += (pesect[PEOBJ_SECT_PDATA].size = 16);
+  pesect[PEOBJ_SECT_PDATA].relocofs = sofs;
+  sofs += (pesect[PEOBJ_SECT_PDATA].nreloc = 4) * PEOBJ_RELOC_SIZE;
+  #endif
   /* Flags: 40 = read, 30 = align4, 40 = initialized data. */
   pesect[PEOBJ_SECT_PDATA].flags = 0x40300040;
 
   memcpy(pesect[PEOBJ_SECT_XDATA].name, ".xdata", sizeof(".xdata")-1);
   pesect[PEOBJ_SECT_XDATA].ofs = sofs;
+#if LJ_TARGET_X64
   sofs += (pesect[PEOBJ_SECT_XDATA].size = 8*2+4+6*2);  /* See below. */
+#else
+  sofs += (pesect[PEOBJ_SECT_XDATA].size = sizeof(UnwindInfo)+44+4+4+/**/+sizeof(UnwindInfo)+8);  /* See below. */
+#endif
   pesect[PEOBJ_SECT_XDATA].relocofs = sofs;
   sofs += (pesect[PEOBJ_SECT_XDATA].nreloc = 1) * PEOBJ_RELOC_SIZE;
   /* Flags: 40 = read, 30 = align4, 40 = initialized data. */
@@ -234,7 +264,7 @@
   */
   nrsym = ctx->nrelocsym;
   pehdr.nsyms = 1+PEOBJ_NSECTIONS*2 + 1+ctx->nsym + nrsym;
-#if LJ_TARGET_X64
+#if LJ_TARGET_X64 || LJ_TARGET_ARM64
   pehdr.nsyms += 1;  /* Symbol for lj_err_unwind_win. */
 #endif
 
@@ -257,11 +287,12 @@
     owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
   }
 
-#if LJ_TARGET_X64
+#if LJ_TARGET_X64 || LJ_TARGET_ARM64
   { /* Write .pdata section. */
+    PEreloc reloc;
     uint32_t fcofs = (uint32_t)ctx->sym[ctx->nsym-1].ofs;
+    #if LJ_TARGET_X64
     uint32_t pdata[3];  /* Start of .text, end of .text and .xdata. */
-    PEreloc reloc;
     pdata[0] = 0; pdata[1] = fcofs; pdata[2] = 0;
     owrite(ctx, &pdata, sizeof(pdata));
     pdata[0] = fcofs; pdata[1] = (uint32_t)ctx->codesz; pdata[2] = 20;
@@ -284,7 +315,34 @@
     reloc.vaddr = 20; reloc.symidx = 1+2+nrsym+2;
     reloc.type = PEOBJ_RELOC_ADDR32NB;
     owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
+    #else
+    uint32_t pdata[4];
+    pdata[0] = 0;
+    pdata[1] = 0;
+    pdata[2] = fcofs;
+    pdata[3] = sizeof(UnwindInfo)+44+4+4;
+    owrite(ctx, &pdata, sizeof(pdata));
+
+    /* Mark the .text */
+    reloc.vaddr = 0; reloc.symidx = 1+2+nrsym+2+2+1;
+    reloc.type = PEOBJ_RELOC_ADDR32NB;
+    owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
+    /* Mark the exception VA address as in .xdata section */
+    reloc.vaddr = 4; reloc.symidx = 1+2+nrsym+2;
+    reloc.type = PEOBJ_RELOC_ADDR32NB;
+    owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
+
+    /* Mark the vm_ffi_call function which requires special unwinding */
+    reloc.vaddr = 8; reloc.symidx = 1+2+nrsym+2+2+1;
+    reloc.type = PEOBJ_RELOC_ADDR32NB;
+    owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
+    /* Mark the exception VA address as in .xdata section */
+    reloc.vaddr = 12; reloc.symidx = 1+2+nrsym+2;
+    reloc.type = PEOBJ_RELOC_ADDR32NB;
+    owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
+    #endif
   }
+#if LJ_TARGET_X64
   { /* Write .xdata section. */
     uint16_t xdata[8+2+6];
     PEreloc reloc;
@@ -308,6 +366,110 @@
     reloc.type = PEOBJ_RELOC_ADDR32NB;
     owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
   }
+#else
+  { /* Write .xdata section. */
+    UnwindInfo ui = {0};
+    uint32_t handler[2];
+    uint8_t codes[64];
+    uint8_t *p;
+    PEreloc reloc;
+    uint32_t fcofs = (uint32_t)ctx->sym[ctx->nsym-1].ofs;
+
+    /* https://learn.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-170#unwind-codes */
+
+    /* 000xxxxx: allocate small stack with size < 512 (2^5 * 16). */
+    #define ALLOC_S(size) do { \
+      *p++ = ((size) / 16) & 0x1f; \
+    } while(0)
+    /* 01zzzzzz: save <x29,lr> pair at [sp+#Z*8], offset <= 504. */
+    #define SAVE_FPLR(offs) do { \
+      *p++ = 0x40 | (((offs) / 8) & 0x1f); \
+    } while(0)
+    /* 110100xx'xxzzzzzz: save reg x(19+#X) at [sp+#Z*8], offset <= 504 */
+    #define SAVE_REG(reg, offs) do { \
+      uint16_t code = 0xd000 | (((reg) - 19) << 6) | ((offs) / 8); \
+      WRITE_CODE16(code); \
+    } while (0)
+    /* 1101110x'xxzzzzzz: save reg d(8+#X) at [sp+#Z*8], offset <= 504 */
+    #define SAVE_FREG(reg, offs) do { \
+      uint16_t code = 0xdc00 | (((reg) - 8) << 6) | ((offs) / 8); \
+      WRITE_CODE16(code); \
+    } while (0)
+    /* 1101010x'xxxzzzzz: save reg x(19+#X) at [sp-(#Z+1)*8]!, pre-indexed offset >= -256 */
+    #define SAVE_REG_X(reg, offs) do { \
+      uint16_t code = 0xd400 | (((reg) - 19) << 5) | (((offs * -1) / 8) - 1); \
+      WRITE_CODE16(code); \
+    } while (0)
+    /* 11100010'xxxxxxxx: set up x29 with add x29,sp,#x*8 */
+    #define ADD_FP(size) do { \
+      uint16_t code = 0xe200 | (((size) / 8) & 0xff); \
+      WRITE_CODE16(code); \
+    } while(0)
+    #define WRITE_CODE16(code) do { \
+      /* the 2-byte code is saved in big endian */ \
+      *p++ = ((code) & 0xff00) >> 8; \
+      *p++ = ((code) & 0xff); \
+    } while (0)
+
+    /* fill the codes with NOP (e3) */
+    memset(codes, 0xe3, sizeof(codes));
+    p = codes;
+    ALLOC_S(208);
+    SAVE_FPLR(192);
+    ADD_FP(192);
+    SAVE_REG(19, 184);
+    SAVE_REG(20, 176);
+    SAVE_REG(21, 168);
+    SAVE_REG(22, 160);
+    SAVE_REG(23, 152);
+    SAVE_REG(24, 144);
+    SAVE_REG(25, 136);
+    SAVE_REG(26, 128);
+    SAVE_REG(27, 120);
+    SAVE_REG(28, 112);
+    SAVE_FREG(8, 104);
+    SAVE_FREG(9, 96);
+    SAVE_FREG(10, 88);
+    SAVE_FREG(11, 80);
+    SAVE_FREG(12, 72);
+    SAVE_FREG(13, 64);
+    SAVE_FREG(14, 56);
+    SAVE_FREG(15, 48);
+    /* end of unwinding codes */
+    *p++ = 0xe4;
+    /* codes must be aligned on 4-byte word */
+    const size_t unwindsize1 = ((p - codes) + 3) & ~3;
+
+    ui.X = 1;
+    ui.CodeWords = unwindsize1 / 4;
+    ui.FunctionLength = fcofs / 4;
+    owrite(ctx, &ui, sizeof(ui));
+    owrite(ctx, &codes, unwindsize1);
+    handler[0] = 0;
+    handler[1] = 0xffffffff;
+    owrite(ctx, &handler, sizeof(handler));
+
+    memset(&ui, 0, sizeof(ui));
+    memset(codes, 0xe3, sizeof(codes));
+
+    p = codes;
+    SAVE_FPLR(16);
+    ADD_FP(16);
+    SAVE_REG_X(19, -24);
+    SAVE_REG_X(20, -32);
+    *p++ = 0xe4;
+    const size_t unwindsize2 = ((p - codes) + 3) & ~3;
+
+    ui.CodeWords = unwindsize2 / 4;
+    ui.FunctionLength = (uint32_t)(ctx->codesz - fcofs) / 4;
+    owrite(ctx, &ui, sizeof(ui));
+    owrite(ctx, &codes, unwindsize2);
+
+    reloc.vaddr = sizeof(ui)+unwindsize1; reloc.symidx = 1+2+nrsym+2+2;
+    reloc.type = PEOBJ_RELOC_ADDR32NB;
+    owrite(ctx, &reloc, PEOBJ_RELOC_SIZE);
+  }
+#endif
 #elif LJ_TARGET_X86
   /* Write .sxdata section. */
   for (i = 0; i < nrsym; i++) {
@@ -339,7 +501,7 @@
       emit_peobj_sym(ctx, ctx->relocsym[i], 0,
 		     PEOBJ_SECT_UNDEF, PEOBJ_TYPE_FUNC, PEOBJ_SCL_EXTERN);
 
-#if LJ_TARGET_X64
+#if LJ_TARGET_X64 || LJ_TARGET_ARM64
     emit_peobj_sym_sect(ctx, pesect, PEOBJ_SECT_PDATA);
     emit_peobj_sym_sect(ctx, pesect, PEOBJ_SECT_XDATA);
     emit_peobj_sym(ctx, "lj_err_unwind_win", 0,
```

**Comment by stuta** [comment]
I was able to compile and run Windows 11 arm using UTM in OSX.

String concatenation does not work. This works: 
`package.path = "lib/?.lua;lib/?.lx;"` 
This does not work: 
`package.path = "lib/?.lua;lib/?.lx;" .. package.path`.
No error, no crash, the program just does not continue.

**Comment by stephenjust** [comment]
> Branches looping back are usually a symptom of missing or wrong relocation records.
> 
> Check the relocation types with `objdump -r` for a trivial object file calling an external function:
> 
> ```c
> extern void foo(void);
> void bar(void) { foo(); }
> ```
> 
> Then compare to `PEOBJ_RELOC_*`.

```
$ objdump -r test.o

test.o: file format coff-arm64

RELOCATION RECORDS FOR [.text]:
OFFSET           TYPE                     VALUE
0000000000000004 IMAGE_REL_ARM64_BRANCH26 foo

RELOCATION RECORDS FOR [.pdata]:
OFFSET           TYPE                     VALUE
0000000000000000 IMAGE_REL_ARM64_ADDR32NB .text
```

**Comment by stephenjust** [comment]
Changing to BRANCH26 made no difference. I am wondering if dasm is incorrectly building the target address. I also don't understand what the PEOBJ_RELOC_OFS value should be, changing it to -4, 0, 4 seems to have no effect.

**Comment by MikePall** [comment]
I've cobbled together an initial version from the different patches and added some more fixes. Unwinding ought to work, too. The output of `llvm-objdump` looks good.

It only works for native ARM64 Visual Studio builds for now. Since I don't have the target environment, I can't test this.

Closing here. Further discussion in #593.

**Pull request closed without merging**
