### PR TITLE
Fix error in const pointer load on ARM64 code generator

### PR DESCRIPTION
**Pull request by zhongweiy**
Fix 2 errors in ldr instruction emit on ARM64.

### CODE REVIEW

**Comment by MikePall** [comment]
Applied. Thanks!

**Comment by zhongweiy** [comment]
Thanks!

**Comment by zhongweiy** [comment]
@MikePall , I added another related fix in this same pull request several hours ago: https://github.com/LuaJIT/LuaJIT/pull/249/commits/6e1b91556323dd80fbb38a21286d9ab8ec57e0f2

Could you please take a look again? Thanks!

**Comment by MikePall** [comment]
Oops, missed that. Applied. Thanks!

**Comment by zhongweiy** [comment]
OK, great!

**Pull request closed without merging**
