### PR TITLE
patterns better compatibility with 5.2

### PR DESCRIPTION
**Pull request by fperrad**

### CODE REVIEW

**Comment by MikePall** [comment]
Apart from the added complexity -- what are the performance implications?

**Comment by fperrad** [comment]
The functional change comes with the [first commit](https://github.com/LuaJIT/LuaJIT/pull/364/commits/bf78e6f97dccf85152e6bd8d43a2c70cf26393bf); and I don't see any additional complexity in it.
With the 2 other commits, it is up to you.

**Comment by timofonic** [comment]
@fperrad @MikePall Any news about this?

**Comment by MikePall** [comment]
Buggy. Soon obsolete with the pattern matching compiler/rewrite.

**Pull request closed without merging**
