### PR TITLE
Disable os.execute() when building for iOS >= 8.0.

### PR DESCRIPTION
**Pull request by mraleph**
This fixes the following deprecation warning when building for iOS

```
lib_os.c:52:14: warning: 'system' is deprecated: first deprecated in iOS 8.0 -
      Use posix_spawn APIs instead. [-Wdeprecated-declarations]
  int stat = system(cmd);
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/usr/include/stdlib.h:177:6: note:
      'system' has been explicitly marked deprecated here
int      system(const char *) __DARWIN_ALIAS_C(system) __OSX_AVAILABLE_B...
         ^
1 warning generated.
```

Fixes issue #3.

### CODE REVIEW

**Comment by mraleph** [comment]
Alternatively we could just disable `os.execute()` on `LJ_TARGET_IOS` altogether.

**Comment by slime73** [comment]
I believe this should use `__IPHONE_OS_VERSION_MIN_REQUIRED` rather than `__IPHONE_OS_VERSION_MAX_ALLOWED`. The former is the deployment target, and the latter is effectively the current SDK version. The deprecation warning will only appear if the deployment target is >= iOS 8.0, and the `system` call should still work on older operating systems even when building with a newer SDK.

**Comment by mraleph** [comment]
@slime73  

Confirmed your interpretation of the defines by compiling with `IPHONEOS_DEPLOYMENT_TARGET` set to `7.0` and to `8.0`.

My interpretation was that `MIN_REQUIRED` and `MAX_ALLOWED` form an interval and warning is shown for anything within that interval, but apparently it's not the case. 

Thanks.

**Comment by MikePall** [comment]
Applied.

**Pull request closed without merging**
